In [2]:
import numpy

In [3]:
list=[1,2,3,4,5]

In [4]:
type(list)

list

In [5]:
array=numpy.array(list)

In [6]:
type(array)

numpy.ndarray

In [7]:
array

array([1, 2, 3, 4, 5])

In [8]:
array.ndim

1

In [10]:
array.shape

(5,)

In [11]:
list=[1,2,3,"sam","hie",123]

In [12]:
arr=numpy.array(list)

In [13]:
arr

array(['1', '2', '3', 'sam', 'hie', '123'], dtype='<U11')

In [14]:
type(arr)

numpy.ndarray

In [16]:
list=(1,2,3,4,5,6,7,8)

In [17]:
arrid=numpy.array(list)

In [18]:
arrid

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
arrid[2:6]

array([3, 4, 5, 6])

In [20]:
list1=[[1,2,3],[3,4,5],[6,7,8]]

In [24]:
arr2d=numpy.array(list1)

In [25]:
arr2d

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
arr2d.shape

(3, 3)

In [27]:
arr2d.ndim

2

In [28]:
arr2d[0]

array([1, 2, 3])

In [29]:
arr2d[1]

array([3, 4, 5])

In [30]:
arr2d[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [31]:
arr2d[0:]

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
arr2d[:,1]

array([2, 4, 7])

In [35]:
#row numbers= 1,2
#col number =1,2
arr2d[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [36]:
arr2d[0,1]

2

In [38]:
list=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [39]:
arr2=numpy.array(list)

In [40]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
arr2[:,2:5]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [49]:
arr2.diagonal(0)    #to get diagonal values

array([ 1,  6, 11, 16])

In [52]:
zero=numpy.zeros((4,5))

In [53]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
one=numpy.ones((4,4))

In [59]:
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
a=numpy.arange(30,40)

In [56]:
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [60]:
a=numpy.arange(40,50,2)

In [61]:
a

array([40, 42, 44, 46, 48])

In [62]:
a=numpy.arange(16)

In [63]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
#2d array with arrange
array1=numpy.arange(16)

In [68]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [69]:
array1.ndim

1

In [70]:
array2=array1.reshape(4,4)  #factors of elementspresent in 1D

In [71]:
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
array2=array1.reshape(2,8)

In [73]:
array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [77]:
array3=numpy.arange(20).reshape(10,2)

In [78]:
array3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [79]:
a=numpy.random.rand(3)

In [80]:
a

array([0.84272064, 0.7732019 , 0.75204903])

In [81]:
a=numpy.random.rand(4,5)

In [82]:
a

array([[0.08876256, 0.51661568, 0.4274636 , 0.25725046, 0.1912506 ],
       [0.66765404, 0.65142009, 0.22296541, 0.54703221, 0.10941326],
       [0.09771884, 0.22595529, 0.92891467, 0.49232277, 0.81014611],
       [0.30108133, 0.53698694, 0.38868628, 0.86955256, 0.92086565]])

In [94]:
numpy.random.randint(10,15)

14

In [96]:
numpy.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [97]:
numpy.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [99]:
a=numpy.arange(0,9).reshape(3,3)

In [100]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
b=numpy.arange(9,18).reshape(3,3)

In [105]:
b

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [107]:
f=numpy.concatenate((a,b))

In [108]:
f

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [109]:
f=numpy.concatenate((a,b),axis=1)

In [110]:
f

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [111]:
flatten=f.flatten()


In [112]:
flatten

array([ 0,  1,  2,  9, 10, 11,  3,  4,  5, 12, 13, 14,  6,  7,  8, 15, 16,
       17])

In [113]:
ravel=f.ravel()

In [117]:
ravel

array([30,  1,  2,  9, 10, 11,  3,  4,  5, 12, 13, 14,  6,  7,  8, 15, 16,
       17])

In [118]:
flatten[0]=22

In [119]:
flatten

array([22,  1,  2,  9, 10, 11,  3,  4,  5, 12, 13, 14,  6,  7,  8, 15, 16,
       17])

In [120]:
f

array([[30,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [121]:
ravel[2]=75

In [122]:
ravel

array([30,  1, 75,  9, 10, 11,  3,  4,  5, 12, 13, 14,  6,  7,  8, 15, 16,
       17])

In [123]:
f

array([[30,  1, 75,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [124]:
k=numpy.transpose(f)

In [125]:
k

array([[30,  3,  6],
       [ 1,  4,  7],
       [75,  5,  8],
       [ 9, 12, 15],
       [10, 13, 16],
       [11, 14, 17]])

In [127]:
mat = numpy.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [143]:
mat[2:6,1:6]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [144]:
mat[3,4]

20

In [150]:
mat[:,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [153]:
mat[4,0:5]

array([21, 22, 23, 24, 25])

In [154]:
mat[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])